version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elk_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms10g -Xmx10g"
      - "cluster.routing.allocation.disk.watermark.low=85%"
      - "cluster.routing.allocation.disk.watermark.high=90%"
      - "cluster.routing.allocation.disk.watermark.flood_stage=95%"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - elastic_net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.1
    container_name: elk_logstash
    volumes:
      - ./configs/logstash:/usr/share/logstash/pipeline
    ports:
      - ${LOGSTASH_PORT}:${LOGSTASH_PORT}
      - 9601:9601
    networks:
      - elastic_net
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: elk_kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    networks:
      - elastic_net

  flask_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elk_flask_api
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - logstash
    networks:
      - elastic_net

networks:
  elastic_net:
    driver: bridge